### ISSUE TITLE
fortress-web dependency errors

### ISSUE THREAD

**Issue by jallmitch** [shawnmckinney/apache-fortress-demo#6]
In attempting to build the java-doc using mvn, I am getting the following error:

---

[WARNING] The POM for org.apache.directory.fortress:fortress-realm-impl:jar:1.0-RC41-SNAPSHOT is missing, no dependency information available
Downloading: http://repo1.maven.org/maven2/org/apache/directory/fortress/fortress-web/1.0/fortress-web-1.0.pom
Downloading: https://repo.maven.apache.org/maven2/org/apache/directory/fortress/fortress-web/1.0/fortress-web-1.0.pom
[WARNING] The POM for org.apache.directory.fortress:fortress-web:jar:classes:1.0 is missing, no dependency information available
Downloading: http://repo1.maven.org/maven2/org/apache/directory/fortress/fortress-web/1.0/fortress-web-1.0-classes.jar
Downloading: https://repo.maven.apache.org/maven2/org/apache/directory/fortress/fortress-web/1.0/fortress-web-1.0-classes.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.668 s
[INFO] Finished at: 2015-11-04T11:06:27-06:00
[INFO] Final Memory: 16M/89M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project fortress-web: Could not resolve dependencies for project org.apache.directory.fortress:fortress-web:war:1.0-RC41-SNAPSHOT: The following artifacts could not be resolved: org.apache.directory.fortress:fortress-realm-impl:jar:1.0-RC41-SNAPSHOT, org.apache.directory.fortress:fortress-web:jar:classes:1.0: Failure to find org.apache.directory.fortress:fortress-realm-impl:jar:1.0-RC41-SNAPSHOT in http://repo1.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of maven2 has elapsed or updates are forced -> [Help 1]

---

I attempted to go to the following url: https://repo1.maven.org/maven2/org/apache/directory/fortress/
and 'fortress-core' is the only directory available, 'fortress-web' does not exist.

**Comment by shawnmckinney** [comment]
Did you complete the steps of the apache fortress 10 minute guide?  It is a rereq for the apache fortress demo app.
